//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Shippy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://shippy.org/", ConfigurationName="Shippy.ShippySoap")]
    public interface ShippySoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://shippy.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://shippy.org/InsertShipmentData", ReplyAction="*")]
        WebProject.Shippy.InsertShipmentDataResponse InsertShipmentData(WebProject.Shippy.InsertShipmentDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://shippy.org/InsertShipmentData", ReplyAction="*")]
        System.Threading.Tasks.Task<WebProject.Shippy.InsertShipmentDataResponse> InsertShipmentDataAsync(WebProject.Shippy.InsertShipmentDataRequest request);
        
        // CODEGEN: Generating message contract since element name orderId from namespace http://shippy.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://shippy.org/DeleteShipmentData", ReplyAction="*")]
        WebProject.Shippy.DeleteShipmentDataResponse DeleteShipmentData(WebProject.Shippy.DeleteShipmentDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://shippy.org/DeleteShipmentData", ReplyAction="*")]
        System.Threading.Tasks.Task<WebProject.Shippy.DeleteShipmentDataResponse> DeleteShipmentDataAsync(WebProject.Shippy.DeleteShipmentDataRequest request);
        
        // CODEGEN: Generating message contract since element name orderId from namespace http://shippy.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://shippy.org/ReadShipmentIdByOrderIdAndProductName", ReplyAction="*")]
        WebProject.Shippy.ReadShipmentIdByOrderIdAndProductNameResponse ReadShipmentIdByOrderIdAndProductName(WebProject.Shippy.ReadShipmentIdByOrderIdAndProductNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://shippy.org/ReadShipmentIdByOrderIdAndProductName", ReplyAction="*")]
        System.Threading.Tasks.Task<WebProject.Shippy.ReadShipmentIdByOrderIdAndProductNameResponse> ReadShipmentIdByOrderIdAndProductNameAsync(WebProject.Shippy.ReadShipmentIdByOrderIdAndProductNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertShipmentDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertShipmentData", Namespace="http://shippy.org/", Order=0)]
        public WebProject.Shippy.InsertShipmentDataRequestBody Body;
        
        public InsertShipmentDataRequest() {
        }
        
        public InsertShipmentDataRequest(WebProject.Shippy.InsertShipmentDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://shippy.org/")]
    public partial class InsertShipmentDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string seller;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string productName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string orderDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int productQuantity;
        
        public InsertShipmentDataRequestBody() {
        }
        
        public InsertShipmentDataRequestBody(string userName, string seller, string address, string city, string productName, string orderDate, string orderId, int productQuantity) {
            this.userName = userName;
            this.seller = seller;
            this.address = address;
            this.city = city;
            this.productName = productName;
            this.orderDate = orderDate;
            this.orderId = orderId;
            this.productQuantity = productQuantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertShipmentDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertShipmentDataResponse", Namespace="http://shippy.org/", Order=0)]
        public WebProject.Shippy.InsertShipmentDataResponseBody Body;
        
        public InsertShipmentDataResponse() {
        }
        
        public InsertShipmentDataResponse(WebProject.Shippy.InsertShipmentDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertShipmentDataResponseBody {
        
        public InsertShipmentDataResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteShipmentDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteShipmentData", Namespace="http://shippy.org/", Order=0)]
        public WebProject.Shippy.DeleteShipmentDataRequestBody Body;
        
        public DeleteShipmentDataRequest() {
        }
        
        public DeleteShipmentDataRequest(WebProject.Shippy.DeleteShipmentDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://shippy.org/")]
    public partial class DeleteShipmentDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string productName;
        
        public DeleteShipmentDataRequestBody() {
        }
        
        public DeleteShipmentDataRequestBody(string orderId, string productName) {
            this.orderId = orderId;
            this.productName = productName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteShipmentDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteShipmentDataResponse", Namespace="http://shippy.org/", Order=0)]
        public WebProject.Shippy.DeleteShipmentDataResponseBody Body;
        
        public DeleteShipmentDataResponse() {
        }
        
        public DeleteShipmentDataResponse(WebProject.Shippy.DeleteShipmentDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteShipmentDataResponseBody {
        
        public DeleteShipmentDataResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadShipmentIdByOrderIdAndProductNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadShipmentIdByOrderIdAndProductName", Namespace="http://shippy.org/", Order=0)]
        public WebProject.Shippy.ReadShipmentIdByOrderIdAndProductNameRequestBody Body;
        
        public ReadShipmentIdByOrderIdAndProductNameRequest() {
        }
        
        public ReadShipmentIdByOrderIdAndProductNameRequest(WebProject.Shippy.ReadShipmentIdByOrderIdAndProductNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://shippy.org/")]
    public partial class ReadShipmentIdByOrderIdAndProductNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string productName;
        
        public ReadShipmentIdByOrderIdAndProductNameRequestBody() {
        }
        
        public ReadShipmentIdByOrderIdAndProductNameRequestBody(string orderId, string productName) {
            this.orderId = orderId;
            this.productName = productName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadShipmentIdByOrderIdAndProductNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadShipmentIdByOrderIdAndProductNameResponse", Namespace="http://shippy.org/", Order=0)]
        public WebProject.Shippy.ReadShipmentIdByOrderIdAndProductNameResponseBody Body;
        
        public ReadShipmentIdByOrderIdAndProductNameResponse() {
        }
        
        public ReadShipmentIdByOrderIdAndProductNameResponse(WebProject.Shippy.ReadShipmentIdByOrderIdAndProductNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://shippy.org/")]
    public partial class ReadShipmentIdByOrderIdAndProductNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReadShipmentIdByOrderIdAndProductNameResult;
        
        public ReadShipmentIdByOrderIdAndProductNameResponseBody() {
        }
        
        public ReadShipmentIdByOrderIdAndProductNameResponseBody(string ReadShipmentIdByOrderIdAndProductNameResult) {
            this.ReadShipmentIdByOrderIdAndProductNameResult = ReadShipmentIdByOrderIdAndProductNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ShippySoapChannel : WebProject.Shippy.ShippySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShippySoapClient : System.ServiceModel.ClientBase<WebProject.Shippy.ShippySoap>, WebProject.Shippy.ShippySoap {
        
        public ShippySoapClient() {
        }
        
        public ShippySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShippySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShippySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShippySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebProject.Shippy.InsertShipmentDataResponse WebProject.Shippy.ShippySoap.InsertShipmentData(WebProject.Shippy.InsertShipmentDataRequest request) {
            return base.Channel.InsertShipmentData(request);
        }
        
        public void InsertShipmentData(string userName, string seller, string address, string city, string productName, string orderDate, string orderId, int productQuantity) {
            WebProject.Shippy.InsertShipmentDataRequest inValue = new WebProject.Shippy.InsertShipmentDataRequest();
            inValue.Body = new WebProject.Shippy.InsertShipmentDataRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.seller = seller;
            inValue.Body.address = address;
            inValue.Body.city = city;
            inValue.Body.productName = productName;
            inValue.Body.orderDate = orderDate;
            inValue.Body.orderId = orderId;
            inValue.Body.productQuantity = productQuantity;
            WebProject.Shippy.InsertShipmentDataResponse retVal = ((WebProject.Shippy.ShippySoap)(this)).InsertShipmentData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebProject.Shippy.InsertShipmentDataResponse> WebProject.Shippy.ShippySoap.InsertShipmentDataAsync(WebProject.Shippy.InsertShipmentDataRequest request) {
            return base.Channel.InsertShipmentDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebProject.Shippy.InsertShipmentDataResponse> InsertShipmentDataAsync(string userName, string seller, string address, string city, string productName, string orderDate, string orderId, int productQuantity) {
            WebProject.Shippy.InsertShipmentDataRequest inValue = new WebProject.Shippy.InsertShipmentDataRequest();
            inValue.Body = new WebProject.Shippy.InsertShipmentDataRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.seller = seller;
            inValue.Body.address = address;
            inValue.Body.city = city;
            inValue.Body.productName = productName;
            inValue.Body.orderDate = orderDate;
            inValue.Body.orderId = orderId;
            inValue.Body.productQuantity = productQuantity;
            return ((WebProject.Shippy.ShippySoap)(this)).InsertShipmentDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebProject.Shippy.DeleteShipmentDataResponse WebProject.Shippy.ShippySoap.DeleteShipmentData(WebProject.Shippy.DeleteShipmentDataRequest request) {
            return base.Channel.DeleteShipmentData(request);
        }
        
        public void DeleteShipmentData(string orderId, string productName) {
            WebProject.Shippy.DeleteShipmentDataRequest inValue = new WebProject.Shippy.DeleteShipmentDataRequest();
            inValue.Body = new WebProject.Shippy.DeleteShipmentDataRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.productName = productName;
            WebProject.Shippy.DeleteShipmentDataResponse retVal = ((WebProject.Shippy.ShippySoap)(this)).DeleteShipmentData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebProject.Shippy.DeleteShipmentDataResponse> WebProject.Shippy.ShippySoap.DeleteShipmentDataAsync(WebProject.Shippy.DeleteShipmentDataRequest request) {
            return base.Channel.DeleteShipmentDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebProject.Shippy.DeleteShipmentDataResponse> DeleteShipmentDataAsync(string orderId, string productName) {
            WebProject.Shippy.DeleteShipmentDataRequest inValue = new WebProject.Shippy.DeleteShipmentDataRequest();
            inValue.Body = new WebProject.Shippy.DeleteShipmentDataRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.productName = productName;
            return ((WebProject.Shippy.ShippySoap)(this)).DeleteShipmentDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebProject.Shippy.ReadShipmentIdByOrderIdAndProductNameResponse WebProject.Shippy.ShippySoap.ReadShipmentIdByOrderIdAndProductName(WebProject.Shippy.ReadShipmentIdByOrderIdAndProductNameRequest request) {
            return base.Channel.ReadShipmentIdByOrderIdAndProductName(request);
        }
        
        public string ReadShipmentIdByOrderIdAndProductName(string orderId, string productName) {
            WebProject.Shippy.ReadShipmentIdByOrderIdAndProductNameRequest inValue = new WebProject.Shippy.ReadShipmentIdByOrderIdAndProductNameRequest();
            inValue.Body = new WebProject.Shippy.ReadShipmentIdByOrderIdAndProductNameRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.productName = productName;
            WebProject.Shippy.ReadShipmentIdByOrderIdAndProductNameResponse retVal = ((WebProject.Shippy.ShippySoap)(this)).ReadShipmentIdByOrderIdAndProductName(inValue);
            return retVal.Body.ReadShipmentIdByOrderIdAndProductNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebProject.Shippy.ReadShipmentIdByOrderIdAndProductNameResponse> WebProject.Shippy.ShippySoap.ReadShipmentIdByOrderIdAndProductNameAsync(WebProject.Shippy.ReadShipmentIdByOrderIdAndProductNameRequest request) {
            return base.Channel.ReadShipmentIdByOrderIdAndProductNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebProject.Shippy.ReadShipmentIdByOrderIdAndProductNameResponse> ReadShipmentIdByOrderIdAndProductNameAsync(string orderId, string productName) {
            WebProject.Shippy.ReadShipmentIdByOrderIdAndProductNameRequest inValue = new WebProject.Shippy.ReadShipmentIdByOrderIdAndProductNameRequest();
            inValue.Body = new WebProject.Shippy.ReadShipmentIdByOrderIdAndProductNameRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.productName = productName;
            return ((WebProject.Shippy.ShippySoap)(this)).ReadShipmentIdByOrderIdAndProductNameAsync(inValue);
        }
    }
}
